Repository wwh-techcamp-2018/team5-fiveMasterGuys, pull requests merged in 2018-08, with the labels that each got.

#73 feat: Create Recipe (#13)
  src/main/java/com/woowahan/techcamp/recipehub/category/domain/Category.java
  src/main/java/com/woowahan/techcamp/recipehub/category/repository/CategoryRepository.java
  src/main/java/com/woowahan/techcamp/recipehub/common/support/WebControllerAdvice.java
  src/main/java/com/woowahan/techcamp/recipehub/recipe/controller/CategoryService.java
  src/main/java/com/woowahan/techcamp/recipehub/recipe/controller/RecipeController.java
  src/main/java/com/woowahan/techcamp/recipehub/recipe/domain/Recipe.java
  src/main/java/com/woowahan/techcamp/recipehub/recipe/dto/RecipeCreationDTO.java
  src/main/java/com/woowahan/techcamp/recipehub/recipe/service/RecipeService.java
  src/main/resources/static/css/common.css
  src/main/resources/static/css/recipe-create.css
  src/main/resources/static/img/hero-create.jpg
  src/main/resources/static/js/recipes/create.js
  src/main/resources/templates/base.hbs
  src/main/resources/templates/recipe-create.hbs
  src/main/resources/templates/support/badrequest.hbs
  src/main/resources/templates/support/notfound.hbs
  src/test/java/com/woowahan/techcamp/recipehub/recipe/controller/RecipeAcceptanceTest.java
  src/test/java/com/woowahan/techcamp/recipehub/recipe/dto/RecipeCreationDTOTest.java
  src/test/java/com/woowahan/techcamp/recipehub/recipe/service/RecipeServiceTest.java
Labels: feat

#81 fix: fix user binding in @AuthRequired interceptor
  src/main/java/com/woowahan/techcamp/recipehub/common/security/AuthRequiredInterceptor.java
  src/main/resources/application.properties
  src/test/java/com/woowahan/techcamp/recipehub/common/security/AuthRequiredInterceptorTest.java
Labels: fix

#90 test: Increase test coverage
  src/main/java/com/woowahan/techcamp/recipehub/recipe/controller/RecipeRestController.java
  src/main/java/com/woowahan/techcamp/recipehub/recipe/dto/RecipeResponseDTO.java
  src/test/java/com/woowahan/techcamp/recipehub/common/security/BasicAuthInterceptorTest.java
  src/test/java/com/woowahan/techcamp/recipehub/home/HomeAcceptanceTest.java
  src/test/java/com/woowahan/techcamp/recipehub/recipe/controller/RecipeAcceptanceTest.java
  src/test/java/com/woowahan/techcamp/recipehub/recipe/controller/RecipeRestAcceptanceTest.java
  src/test/java/com/woowahan/techcamp/recipehub/recipe/dto/RecipeResponseDTOTest.java
  src/test/java/com/woowahan/techcamp/recipehub/step/converter/StepContentConverterTest.java
  src/test/java/com/woowahan/techcamp/recipehub/step/dto/StepResponseDTOTest.java
  src/test/java/com/woowahan/techcamp/recipehub/support/SessionUtilsTest.java
  src/test/java/com/woowahan/techcamp/recipehub/user/dto/SignupDTOTest.java
Labels: test

#111 Feat: recipe view design 2nd (Re)
  src/main/java/com/woowahan/techcamp/recipehub/recipe/controller/RecipeController.java
  src/main/resources/static/css/recipe-detail.css
  src/main/resources/static/js/common.js
  src/main/resources/static/js/steps/step.js
  src/main/resources/static/js/steps/templates.js
  src/main/resources/static/js/users/signup.js
  src/main/resources/templates/base.hbs
  src/main/resources/templates/recipe-completed.hbs
  src/main/resources/templates/recipe/addBtn.hbs
  src/main/resources/templates/recipe/completed.hbs
  src/main/resources/templates/recipe/create.hbs
  src/main/resources/templates/recipe/incompleted.hbs
  src/main/resources/templates/recipe/recipe.hbs
  src/main/resources/templates/recipe/step.hbs
  src/main/resources/templates/recipe/stepBox.hbs
  src/main/resources/templates/recipe/stepOffer.hbs
Labels: chore

#168 fix: Fix css bug
  src/main/resources/static/css/recipe-detail.css
Labels: hotfix

#188 fix: Remove unnecessary line
  src/main/resources/static/css/home.css
Labels: hotfix

#196 fix: Render category with server-side and update search with category
  src/main/java/com/woowahan/techcamp/recipehub/category/controller/CategoryRestController.java
  src/main/java/com/woowahan/techcamp/recipehub/home/controller/HomeController.java
  src/main/resources/static/js/category/category.js
  src/main/resources/templates/index.hbs
  src/test/java/com/woowahan/techcamp/recipehub/category/controller/CategoryRestAcceptanceTest.java
  src/test/java/com/woowahan/techcamp/recipehub/home/HomeAcceptanceTest.java
Labels: fix
